services:
  db:
    image: postgres:18-alpine
    container_name: my-hitster-postgres
    restart: always
    ports:
      - "5500:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - hitster_postgres_data:/var/lib/postgresql/data

volumes:
  hitster_postgres_data: